version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_VAULT_URL: http://vault:8201
      KC_VAULT_TOKEN: ${VAULT_TOKEN:-root}
      KC_VAULT_KEY_PATH: secret/data/keycloak/keys/signing
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - vault
    networks:
      - app-network
    restart: unless-stopped

  vault:
    image: hashicorp/vault:1.14
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8201:8201"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8201
    command: server -dev -dev-listen-address=0.0.0.0:8201
    volumes:
      - vault_data:/vault/data
    networks:
      - app-network
    restart: unless-stopped

  key-rotation:
    image: alpine:latest
    container_name: key-rotation
    volumes:
      - ./scripts:/scripts
    depends_on:
      - vault
      - keycloak
    environment:
      - VAULT_ADDR=http://vault:8201
      - VAULT_TOKEN=root
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - REALM=master
    networks:
      - app-network
    entrypoint: /bin/sh
    command: -c "apk add --no-cache curl openssl bash coreutils jq && chmod +x /scripts/*.sh && echo 'Waiting for Vault and Keycloak to start...' && sleep 15 && echo 'Initializing Vault...' && /scripts/init-vault.sh && echo 'Generating initial keys...' && /scripts/rotate-keys-with-history.sh && echo 'Creating custom realm with Vault keys...' && /scripts/create-custom-realm.sh && echo 'Setting up Keycloak Provider...' && /scripts/setup-keycloak-provider.sh && echo 'Setup complete! Starting key rotation service...' && while true; do sleep 3600; /scripts/rotate-keys-with-history.sh; done"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  vault_data: 